#!/usr/bin/env python3
"""
Password Setup Utility for RACREC Backend
This script generates a bcrypt hash for the admin password and saves it to .env file
"""

import bcrypt
import os
from pathlib import Path
import getpass

def generate_password_hash(password):
    """Generate bcrypt hash from password"""
    # Generate salt and hash the password
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def save_to_env(password_hash):
    """Save password hash to .env file"""
    env_path = Path(__file__).parent / '.env'
    
    # Create or update .env file
    with open(env_path, 'w') as f:
        f.write(f"# Backend Environment Variables\n")
        f.write(f"# Generated by setup_password.py\n\n")
        f.write(f"ADMIN_PASSWORD_HASH={password_hash}\n")
    
    print(f"\n✅ Password hash saved to {env_path}")
    print(f"⚠️  Keep this file secure and do NOT commit it to Git!")

def main():
    print("=" * 60)
    print("RACREC Backend - Password Setup")
    print("=" * 60)
    print("\nThis utility will generate a secure bcrypt hash for your admin password.")
    print("The hash will be saved to a .env file.\n")
    
    # Get password from user
    while True:
        password = getpass.getpass("Enter admin password: ")
        confirm_password = getpass.getpass("Confirm password: ")
        
        if password != confirm_password:
            print("❌ Passwords don't match. Please try again.\n")
            continue
        
        if len(password) < 8:
            print("❌ Password must be at least 8 characters long.\n")
            continue
        
        break
    
    print("\n🔐 Generating secure password hash...")
    password_hash = generate_password_hash(password)
    
    print(f"✅ Hash generated successfully!")
    print(f"\nYour password hash:")
    print(f"{password_hash}\n")
    
    # Save to .env
    save_to_env(password_hash)
    
    print("\n" + "=" * 60)
    print("Setup Complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Restart your Flask backend server")
    print("2. Test login with your password")
    print("3. Make sure .env is in your .gitignore file")
    print("\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
